#!/usr/bin/python

import sys
import os
import subprocess

refname = sys.argv[0]
oldrev = sys.argv[1]
newrev = sys.argv[2]
wd = os.getcwd()
top_level = wd.split('RISCVBusiness')[0]
top_level += 'RISCVBusiness'
subprocess.call(['cd', top_level])
print 'Running tests...'
ret = subprocess.call(['./run_tests.py'])
subprocess.call(['cd', wd])
if !ret:
  print 'Push failed because tests have failed'
  sys.exit(ret)
else:
  print 'All tests have passed'
