#! /usr/bin/env python
#encoding: utf-8

# Add your extension as a directory to recurse into here

def configure(cnf):
  cnf.recurse(template)
  cnf.recurse(test)

def sim_source(cnf):
  cnf.recurse(template)
  cnf.recurse(test)
