#! /usr/bin/env python
#encoding: utf-8

def configure(cnf):
  cnf.recurse(pass_through)
  cnf.recurse(direct_mapped_tpf)

def sim_source(cnf):
  cnf.recurse(pass_through)
  cnf.recurse(direct_mapped_tpf)
